export const createHomeworkResaltsMember = (student) => {
	return {students_name: student.fullName, 
            id: student.id, 
            hw1: 0,
            hw1repo: "",
            hw2: 0,
            hw2repo: "",
            hw3: 0,
            hw3repo: "",
            hw4: 0,
            hw4repo: "",
            hw5: 0,
            hw5repo: "",
            hw6: 0,
            hw6repo: "",
            hw7: 0,
            hw7repo: "",
            hw8: 0,
            hw8repo: "",
            hw9: 0,
            hw9repo: "",
            hw10: 0,
            hw10repo: "",
            hw11: 0,
            hw11repo: "",
            total: 0
	};
};

export const updateHomeworkResaltsMember = (student) => {
	return {students_name: student.fullName, 
            id: student.id,
            hw1: 0,
            hw1repo: "",
            hw2: 0,
            hw2repo: "",
            hw3: 0,
            hw3repo: "",
            hw4: 0,
            hw4repo: "",
            hw5: 0,
            hw5repo: "",
            hw6: 0,
            hw6repo: "",
            hw7: 0,
            hw7repo: "",
            hw8: 0,
            hw8repo: "",
            hw9: 0,
            hw9repo: "",
            hw10: 0,
            hw10repo: "",
            hw11: 0,
            hw11repo: "",
            total: 0
	};
};